#!/usr/bin/env bash
#
# bootstrap installs things.

# exit if non-zero exit code
set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)


echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}


for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.sh')
do
  chmod +x "$src"
done

# Install OMZ and powerlevel10K theme
if [[ ! -d $HOME/.oh-my-zsh ]]; then
  echo "install oh-my-zsh ..."
  $DOTFILES_ROOT/omz/install.sh 2>&1
fi
if [[ ! -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k ]]; then
  echo "install oh-my-zsh p10k theme ..."
  $DOTFILES_ROOT/omz/p10k-install.sh 2>&1
fi

install_dotfiles () {
  info 'installing dotfiles-example'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    ln -sf "$src" "$dst"
  done
}

# Link dot files
install_dotfiles


echo ''
echo '  All installed!'